nome=input('Digite o nome do cliente: ')
diavenc=int(input('Digite o dia do vencimento: '))
mesvenc=input('Digite o mês do vencimento: ')
valorfat=(input('Digite o valor da fatura: '))
print('Olá,', nome)
print('A sua fatura com vencimento em', diavenc, 'de', mesvenc, 'no valor de R$', valorfat, 'está fechada.')
